const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],K='wallkeep.v1';
let db=JSON.parse(localStorage.getItem(K)||'null')||{lists:[],currentListId:null},view='home',game='pokemon',stream=null,rapid=false,busy=false,worker=null,lastCode='',active=null,zoomTrack=null,detectTimer=null,lastQuad=null,stableFrames=0;
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+''+Math.random(),save=()=>{localStorage.setItem(K,JSON.stringify(db));render()},list=x=>db.lists.find(l=>l.id===x),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function newList(n='Nuovo ritiro'){let l={id:id(),name:n,game,createdAt:new Date().toISOString(),cards:[]};db.lists.unshift(l);db.currentListId=l.id;save();return l}
function current(){return list(db.currentListId)||newList($('#scanListName').value||'Nuovo ritiro')}
function go(v){if(view==='scan'&&v!=='scan')stop();view=v;$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$('#backBtn').classList.toggle('hidden',v==='home');$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===v));if(v==='scan')camera();render()}
$$('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));$('#backBtn').onclick=()=>go('home');$('#settingsBtn').onclick=()=>go('settings');setTimeout(()=>$('#splash').classList.add('hide'),1800);$('#splash').onclick=()=>$('#splash').classList.add('hide');navigator.serviceWorker?.register('service-worker.js').catch(()=>{});
async function setZoom(z){if(!zoomTrack)return;let cap=zoomTrack.getCapabilities?.()||{};if(!cap.zoom)return;z=Math.max(cap.zoom.min,Math.min(cap.zoom.max,+z));try{await zoomTrack.applyConstraints({advanced:[{zoom:z}]});$('#zoomRange').value=z;$('#zoomValue').textContent=(Math.round(z*10)/10).toFixed(1)+'×'}catch(e){}}
async function setupZoom(){zoomTrack=stream?.getVideoTracks?.()[0]||null;let cap=zoomTrack?.getCapabilities?.()||{};if(cap.zoom){$('#zoomPanel').classList.remove('hidden');$('#zoomRange').min=cap.zoom.min;$('#zoomRange').max=cap.zoom.max;$('#zoomRange').step=cap.zoom.step||.1;let z=zoomTrack.getSettings?.().zoom||cap.zoom.min;$('#zoomRange').value=z;$('#zoomValue').textContent=(+z).toFixed(1)+'×'}else $('#zoomPanel').classList.add('hidden')}
$('#zoomRange').oninput=e=>setZoom(e.target.value);$$('.zoomPreset').forEach(b=>b.onclick=()=>setZoom(b.dataset.zoom));
async function camera(){if(stream)return;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});$('#video').srcObject=stream;await $('#video').play();await setupZoom();startDetection();$('#scanStatus').textContent='Cerca una carta nell’inquadratura.'}catch(e){$('#scanStatus').innerHTML='<span class=bad>Fotocamera: '+esc(e.message)+'</span>'}}
function stop(){rapid=false;clearInterval(detectTimer);detectTimer=null;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}zoomTrack=null;$('#zoomPanel').classList.add('hidden');$('#rapidBtn').textContent='AVVIA SCANSIONE RAPIDA'}
function orderPts(p){let pts=p.slice(),s=pts.map(x=>x.x+x.y),d=pts.map(x=>x.x-x.y);return[pts[s.indexOf(Math.min(...s))],pts[d.indexOf(Math.max(...d))],pts[s.indexOf(Math.max(...s))],pts[d.indexOf(Math.min(...d))]]}
function quadClose(a,b){if(!a||!b)return false;let d=0;for(let i=0;i<4;i++)d+=Math.hypot(a[i].x-b[i].x,a[i].y-b[i].y);return d/4<14}
function drawQuad(q,w,h){let c=$('#detectOverlay'),box=$('#cameraBox'),r=box.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=r.width*dpr;c.height=r.height*dpr;let x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);if(!q)return;x.scale(dpr,dpr);x.strokeStyle='#f3d17a';x.lineWidth=3;x.shadowColor='#d9ab46';x.shadowBlur=10;x.beginPath();q.forEach((p,i)=>{let px=p.x/w*r.width,py=p.y/h*r.height;i?x.lineTo(px,py):x.moveTo(px,py)});x.closePath();x.stroke()}
function detectCard(){if(!stream||!$('#video').videoWidth||typeof cv==='undefined'||!cv.Mat)return null;let v=$('#video'),c=$('#detectCanvas'),ctx=c.getContext('2d'),W=480,H=Math.round(v.videoHeight*(W/v.videoWidth));c.width=W;c.height=H;ctx.drawImage(v,0,0,W,H);let src=cv.imread(c),gray=new cv.Mat(),blur=new cv.Mat(),edge=new cv.Mat(),contours=new cv.MatVector(),hier=new cv.Mat(),best=null,bestArea=0;try{cv.cvtColor(src,gray,cv.COLOR_RGBA2GRAY);cv.GaussianBlur(gray,blur,new cv.Size(5,5),0);cv.Canny(blur,edge,55,150);cv.findContours(edge,contours,hier,cv.RETR_LIST,cv.CHAIN_APPROX_SIMPLE);for(let i=0;i<contours.size();i++){let cnt=contours.get(i),peri=cv.arcLength(cnt,true),approx=new cv.Mat();cv.approxPolyDP(cnt,approx,.025*peri,true);let area=Math.abs(cv.contourArea(approx));if(approx.rows===4&&area>W*H*.12&&area<W*H*.92&&area>bestArea){let p=[];for(let j=0;j<4;j++)p.push({x:approx.intPtr(j,0)[0],y:approx.intPtr(j,0)[1]});let q=orderPts(p),ww=(Math.hypot(q[0].x-q[1].x,q[0].y-q[1].y)+Math.hypot(q[2].x-q[3].x,q[2].y-q[3].y))/2,hh=(Math.hypot(q[0].x-q[3].x,q[0].y-q[3].y)+Math.hypot(q[1].x-q[2].x,q[1].y-q[2].y))/2,ratio=Math.max(ww,hh)/Math.min(ww,hh);if(ratio>1.25&&ratio<1.7){best=q;bestArea=area}}approx.delete();cnt.delete()}}finally{src.delete();gray.delete();blur.delete();edge.delete();contours.delete();hier.delete()}drawQuad(best,W,H);if(best&&quadClose(best,lastQuad))stableFrames++;else stableFrames=best?1:0;lastQuad=best;return best?{q:best,w:W,h:H,stable:stableFrames>=3}:null}
function startDetection(){clearInterval(detectTimer);detectTimer=setInterval(()=>{let d=detectCard();if(!d){$('#scanStatus').textContent='Cerco i bordi della carta…';return}$('#scanStatus').innerHTML=d.stable?'<span class=good>✓ Carta agganciata</span>':'Tieni ferma la carta…';if(rapid&&d.stable&&!busy)scanDetected(d)},220)}
function warpDetected(d){let src=cv.imread($('#detectCanvas')),dst=new cv.Mat(),srcPts=cv.matFromArray(4,1,cv.CV_32FC2,d.q.flatMap(p=>[p.x,p.y])),dstPts=cv.matFromArray(4,1,cv.CV_32FC2,[0,0,744,0,744,1039,0,1039]),M=cv.getPerspectiveTransform(srcPts,dstPts);cv.warpPerspective(src,dst,M,new cv.Size(744,1039),cv.INTER_LINEAR,cv.BORDER_REPLICATE);cv.imshow('warpCanvas',dst);src.delete();dst.delete();srcPts.delete();dstPts.delete();M.delete();return $('#warpCanvas')}
async function ocr(){if(worker)return worker;$('#scanStatus').textContent='Caricamento OCR…';worker=await Tesseract.createWorker('eng');return worker}
function cropCanvas(src,y0,y1){let c=$('#ocrCanvas'),x=c.getContext('2d'),h=src.height*(y1-y0);c.width=src.width;c.height=h;x.filter='grayscale(1) contrast(1.9)';x.drawImage(src,0,src.height*y0,src.width,h,0,0,c.width,c.height);return c}
function op(t){t=t.toUpperCase().replace(/[–—]/g,'-').replace(/\s+/g,' ');let m=t.match(/\b((?:OP|ST|EB|PRB)\s*-?\s*\d{1,2}\s*-\s*\d{3})\b/);if(m)return m[1].replace(/\s/g,'').replace(/^([A-Z]+)-?(\d+)-/,'$1$2-');m=t.match(/\b(P\s*-\s*\d{3})\b/);return m?m[1].replace(/\s/g,''):null}
function pk(t){let m=t.toUpperCase().replace(/[|]/g,'/').match(/\b([A-Z]{0,4}\d{1,3}[A-Z]?)\s*\/\s*(\d{2,3})\b/);return m?{local:m[1],total:m[2]}:null}
function magicBottom(t){let set=(t.toUpperCase().match(/\b([A-Z0-9]{3,5})\b/g)||[]).find(x=>!/^(EN|IT|JP|FR|DE|ES)$/.test(x));let m=t.match(/\b(\d{1,4}[a-z]?)\s*\/\s*\d{2,4}\b/i)||t.match(/\b(\d{1,4}[a-z]?)\b/i);return{set:set||'',collector:m?m[1]:''}}
async function json(u){let r=await fetch(u,{headers:{Accept:'application/json;q=0.9,*/*;q=0.8'}});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function findOP(code){for(let u of[`https://optcgapi.com/api/sets/card/${encodeURIComponent(code)}/`,`https://optcgapi.com/api/decks/card/${encodeURIComponent(code)}/`])try{let d=await json(u),a=Array.isArray(d)?d:[d];if(a[0])return a.map(x=>({name:x.card_name||x.name||code,setName:x.set_name||x.card_set||'',setCode:code.split('-')[0],collector:code,image:x.card_image||x.image||'',externalId:x.card_image_id||''}))}catch(e){}return[]}
async function findPK(p){let a=await json(`https://api.tcgdex.net/v2/en/cards?localId=eq:${encodeURIComponent(p.local)}`),out=[];for(let b of(Array.isArray(a)?a:[]).slice(0,30))try{let d=await json(`https://api.tcgdex.net/v2/en/cards/${encodeURIComponent(b.id)}`),tot=d?.set?.cardCount?.official||d?.set?.cardCount?.total;if(+tot!==+p.total)continue;out.push({name:d.name||b.name,setName:d.set?.name||'',setCode:d.set?.id||'',collector:d.localId||p.local,image:d.image?d.image+'/high.webp':b.image||'',externalId:d.id})}catch(e){}return out}
async function findMagic(nameText,bottom){let name=(nameText.split(/\r?\n/).map(x=>x.trim()).filter(x=>x.length>2)[0]||'').replace(/[^\w,'’\- ]/g,'').trim();if(bottom.set&&bottom.collector)try{let d=await json(`https://api.scryfall.com/cards/${encodeURIComponent(bottom.set.toLowerCase())}/${encodeURIComponent(bottom.collector)}`);return[{name:d.name,setName:d.set_name,setCode:d.set,collector:d.collector_number,image:d.image_uris?.normal||d.card_faces?.[0]?.image_uris?.normal||'',externalId:d.id}]}catch(e){}if(!name)return[];let d=await json(`https://api.scryfall.com/cards/named?fuzzy=${encodeURIComponent(name)}`);return[{name:d.name,setName:d.set_name,setCode:d.set,collector:d.collector_number,image:d.image_uris?.normal||d.card_faces?.[0]?.image_uris?.normal||'',externalId:d.id}]}
function add(x,cands){let l=current();l.game=game;l.name=$('#scanListName').value||l.name;let same=l.cards.find(c=>c.externalId&&c.externalId===x.externalId&&c.resolved);if(same)same.quantity++;else l.cards.unshift({id:id(),game:game==='pokemon'?'Pokémon':game==='onepiece'?'One Piece':'Magic',quantity:1,condition:'',language:'',foil:'',price:'',resolved:cands.length<=1,candidates:cands.slice(0,8),...x});save();navigator.vibrate?.(55)}
async function scanDetected(d){if(busy)return;busy=true;try{let wc=warpDetected(d),w=await ocr(),bottom=(await w.recognize(cropCanvas(wc,.70,1))).data.text||'',cands=[],code='';if(game==='onepiece'){code=op(bottom);if(code)cands=await findOP(code)}else if(game==='pokemon'){let p=pk(bottom);if(p){code=p.local+'/'+p.total;cands=await findPK(p)}}else{let top=(await w.recognize(cropCanvas(wc,0,.22))).data.text||'',mb=magicBottom(bottom);cands=await findMagic(top,mb);code=cands[0]?.externalId||top.trim()}if(!cands.length){$('#scanStatus').textContent='Carta trovata, ma dati non riconosciuti. Riprova con più luce.';return}if(code===lastCode){$('#scanStatus').textContent='Carta già acquisita: sostituiscila.';return}lastCode=code;add(cands[0],cands);$('#scanStatus').innerHTML='<span class=good>✓ '+esc(cands[0].name)+' acquisita. Carta successiva.</span>';stableFrames=0;lastQuad=null}catch(e){$('#scanStatus').innerHTML='<span class=bad>'+esc(e.message)+'</span>'}finally{busy=false}}
$('#rapidBtn').onclick=async()=>{if(!stream)await camera();rapid=!rapid;$('#rapidBtn').textContent=rapid?'STOP SCANSIONE':'AVVIA SCANSIONE RAPIDA';if(!rapid)lastCode=''};$('#singleBtn').onclick=()=>{let d=detectCard();if(d)scanDetected({...d,stable:true})};$$('.gamebtn').forEach(b=>b.onclick=()=>{game=b.dataset.game;$$('.gamebtn').forEach(x=>x.classList.toggle('active',x===b));lastCode=''});
$('#newScanList').onclick=()=>{let n=prompt('Nome nuova lista:','Nuovo ritiro');if(n){let l=newList(n);$('#scanListName').value=l.name}};$('#scanListName').onchange=()=>{let l=current();l.name=$('#scanListName').value||l.name;save()};$('#createList').onclick=()=>{let n=prompt('Nome lista:','Nuovo ritiro');if(n)newList(n)};function openList(i){active=i;go('listDetail')}
function csv(l){let H=['Name','Game','Set code','Set name','Collector number','Foil','Quantity','Condition','Language','CardTrader EUR'],q=x=>{x=String(x??'');return/[;\n\r"]/.test(x)?'"'+x.replace(/"/g,'""')+'"':x},rows=[H.join(';'),...l.cards.map(c=>[c.name,c.game,c.setCode,c.setName,c.collector,c.foil,c.quantity,c.condition,c.language,c.price].map(q).join(';'))],a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+rows.join('\r\n')],{type:'text/csv'}));a.download=l.name.replace(/[^\w-]+/g,'_')+'.csv';a.click()}
$('#exportList').onclick=()=>{let l=list(active);if(l)csv(l)};$('#applyBulk').onclick=()=>{let l=list(active);if(!l)return;$$('#cardsContainer .cardrow').filter(r=>r.querySelector('.pick').checked).forEach(r=>{let c=l.cards.find(x=>x.id===r.dataset.id);if($('#bulkCondition').value)c.condition=$('#bulkCondition').value;if($('#bulkLanguage').value)c.language=$('#bulkLanguage').value;if($('#bulkFoil').value)c.foil=$('#bulkFoil').value});save()};$('#valueAll').onclick=()=>alert('CardTrader sarà il prossimo collegamento dopo aver stabilizzato il riconoscimento.');$('#importCsv').onclick=()=>$('#csvInput').click();$('#saveSettings').onclick=()=>alert('Impostazioni CardTrader saranno abilitate dopo il test scanner.');$('#testCt').onclick=()=>alert('Prima stabilizziamo il riconoscimento carte.');$('#closeCandidates').onclick=()=>$('#candidateDialog').classList.remove('open');
function render(){let l=list(db.currentListId);$('#scanListName').value=l?.name||'';$('#scanCount').textContent=l?l.cards.reduce((a,c)=>a+(+c.quantity||1),0):0;$('#lastScans').innerHTML=l?l.cards.slice(0,5).map(c=>`<div class=last>${c.image?`<img src="${esc(c.image)}">`:'<div class=thumb></div>'}<div><b>${esc(c.name)}</b><div class=code>${esc(c.collector)}</div><div class=muted>${esc(c.setName)}</div></div><b>x${c.quantity}</b></div>`).join(''):'';$('#listsContainer').innerHTML=db.lists.map(l=>`<div class=list-card><div class=head><div><b>${esc(l.name)}</b><div class=muted>${new Date(l.createdAt).toLocaleDateString('it-IT')} • ${l.cards.reduce((a,c)=>a+(+c.quantity||1),0)} carte</div></div></div><button class="btn secondary openList w100" data-id="${l.id}" style="margin-top:9px">APRI</button></div>`).join('')||'<div class="panel muted">Nessuna lista salvata.</div>';$$('.openList').forEach(b=>b.onclick=()=>openList(b.dataset.id));let d=list(active);if(d){$('#detailName').textContent=d.name;$('#detailMeta').textContent=d.cards.length+' righe';$('#cardsContainer').innerHTML=d.cards.map(c=>`<div class=cardrow data-id="${c.id}"><input class=pick type=checkbox><div><b>${esc(c.name)}</b><div class=code>${esc(c.collector)}</div><div class=fields><select class=cond><option value="">Cond.</option>${['NM','SP','MP','PL','PO'].map(v=>`<option ${c.condition===v?'selected':''}>${v}</option>`).join('')}</select><select class=lang><option value="">Lingua</option>${['EN','IT','JP','FR','DE','ES'].map(v=>`<option ${c.language===v?'selected':''}>${v}</option>`).join('')}</select><select class=foil><option value="">Foil</option><option ${c.foil==='No'?'selected':''}>No</option><option ${c.foil==='Sì'?'selected':''}>Sì</option></select></div></div><div class=price>${c.price?c.price+' €':'—'}</div></div>`).join('')||'<div class=muted>Lista vuota.</div>';$$('#cardsContainer .cardrow').forEach(r=>{let c=d.cards.find(x=>x.id===r.dataset.id);r.querySelector('.cond').onchange=e=>{c.condition=e.target.value;save()};r.querySelector('.lang').onchange=e=>{c.language=e.target.value;save()};r.querySelector('.foil').onchange=e=>{c.foil=e.target.value;save()}})}}render();