/* WallKeep recognition patch v7 */
(function(){
const genericWords=new Set(['set','card','carta','the','di','del','edition','edizione']);
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function qTokens(q){return norm(q).split(/\s+/).filter(t=>t.length>1&&!genericWords.has(t));}
function meaningfulLines(text){return String(text||'').split(/\r?\n/).map(x=>x.replace(/[^A-Za-z0-9.'’\- ]/g,' ').replace(/\s+/g,' ').trim()).filter(x=>x.length>=3);}
function bestName(text){const bad=/^(basic|stage|trainer|supporter|item|energy|creature|instant|sorcery|artifact|enchantment|legendary|character|leader|event|stage|on play)$/i;return meaningfulLines(text).filter(x=>!bad.test(x)&&!/^[0-9 ]+$/.test(x)).sort((a,b)=>{const aw=/^[A-Za-z][A-Za-z.'’\- ]+$/.test(a)?20:0,bw=/^[A-Za-z][A-Za-z.'’\- ]+$/.test(b)?20:0;return bw-aw||a.length-b.length;})[0]||'';}
function namesClose(a,b){a=norm(a);b=norm(b);if(!a||!b)return false;if(a===b||a.includes(b)||b.includes(a))return true;const aa=new Set(a.split(' ')),bb=new Set(b.split(' '));const shared=[...aa].filter(x=>x.length>2&&bb.has(x));return shared.length>=Math.max(1,Math.min(aa.size,bb.size)-1);}
function scoreResult(r,q){const ts=qTokens(q),name=norm(r.name),set=norm((r.setName||'')+' '+(r.setCode||'')),collector=norm(r.collector),hay=name+' '+set+' '+collector;let s=0;for(const t of ts){if(name===t||name.startsWith(t+' '))s+=40;else if(name.includes(t))s+=30;else if(set.includes(t))s+=22;else if(collector.includes(t))s+=18;else if(hay.includes(t))s+=5;}return s;}
function showOcr(top,bottom,full='',extra=''){let el=document.querySelector('#ocrDebug');if(!el){el=document.createElement('details');el.id='ocrDebug';el.className='panel';el.style.marginTop='8px';el.innerHTML='<summary style="cursor:pointer;color:#f3d17a;font-weight:700">Diagnostica OCR</summary><pre id="ocrDebugText" style="white-space:pre-wrap;font-size:11px;color:#aaa;margin:8px 0 0"></pre>';document.querySelector('#scanStatus').insertAdjacentElement('afterend',el)}el.querySelector('#ocrDebugText').textContent='TOP:\n'+top+'\n\nBOTTOM:\n'+bottom+(extra?'\n\nEXTRA:\n'+extra:'')+(full?'\n\nFULL:\n'+full:'');}
function cropRegion(src,x0,y0,x1,y1,scale=3){const c=document.createElement('canvas'),ctx=c.getContext('2d'),sx=src.width*x0,sy=src.height*y0,sw=src.width*(x1-x0),sh=src.height*(y1-y0);c.width=Math.max(1,Math.round(sw*scale));c.height=Math.max(1,Math.round(sh*scale));ctx.filter='grayscale(1) contrast(2.2)';ctx.drawImage(src,sx,sy,sw,sh,0,0,c.width,c.height);return c;}
function extractOPCode(t){const s=String(t||'').toUpperCase().replace(/[–—_]/g,'-').replace(/\s+/g,' ').replace(/O(?=\d)/g,'0').replace(/[IL](?=\d)/g,'1');let m=s.match(/\b((?:OP|ST|EB|PRB)\s*-?\s*\d{1,2}\s*-\s*\d{3})\b/);if(m)return m[1].replace(/\s/g,'').replace(/^([A-Z]+)-?(\d+)-/,'$1$2-');m=s.match(/\b(P\s*-\s*\d{3})\b/);return m?m[1].replace(/\s/g,''):null;}
function relaxedPokemonNumber(t){t=String(t||'').toUpperCase().replace(/O/g,'0');let m=t.match(/\b(\d{1,3}[A-Z]?)\s*[\/\\]\s*(\d{2,3})\b/);return m?{local:m[1],total:m[2]}:null;}
async function searchByName(name){if(!name)return[];try{if(game==='onepiece')return (await searchOP(name)).filter(r=>namesClose(name,r.name)).sort((a,b)=>scoreResult(b,name)-scoreResult(a,name));if(game==='pokemon')return (await searchPokemon(name)).filter(r=>namesClose(name,r.name)).sort((a,b)=>scoreResult(b,name)-scoreResult(a,name));return (await searchMagic(name)).filter(r=>namesClose(name,r.name)).sort((a,b)=>scoreResult(b,name)-scoreResult(a,name));}catch(e){return[]}}
function getLastCard(){const l=current();return l?.cards?.[0]||null;}
function addProvisional(card){card={...card,resolved:false,needsReview:true};const l=current();l.game=game;l.name=$('#scanListName').value||l.name;l.cards.unshift({id:crypto.randomUUID?crypto.randomUUID():Date.now()+''+Math.random(),game:game==='pokemon'?'Pokémon':game==='onepiece'?'One Piece':'Magic',quantity:1,condition:'',language:'',foil:'',price:'',...card});save();navigator.vibrate?.([50,30,50]);}
function addExact(card){add(card,[card]);}
let locked=false,missing=0,lastDet=null,pendingDuplicate=null;
const rawDetect=detectCard;
function clearDuplicateUI(){pendingDuplicate=null;document.querySelector('#duplicateBtn')?.remove();}
function showDuplicate(card,provisional){clearDuplicateUI();pendingDuplicate={card,provisional};const b=document.createElement('button');b.id='duplicateBtn';b.className='btn w100';b.style.marginTop='8px';b.textContent='+ AGGIUNGI UN’ALTRA COPIA DI '+card.name.toUpperCase();b.onclick=()=>{const last=getLastCard();if(last&&namesClose(last.name,card.name)){last.quantity=(+last.quantity||1)+1;save();}else provisional?addProvisional(card):addExact(card);clearDuplicateUI();locked=true;$('#scanStatus').innerHTML='<span class=good>✓ Copia aggiunta. Ora rimuovi la carta.</span>';navigator.vibrate?.([50,30,50]);};$('#scanStatus').insertAdjacentElement('afterend',b);$('#scanStatus').innerHTML='<span class=bad>'+esc(card.name)+' è uguale alla carta precedente. Tocca il pulsante solo se vuoi aggiungere un’altra copia.</span>';}
startDetection=function(){clearInterval(detectTimer);detectTimer=setInterval(()=>{const d=rawDetect();if(d){missing=0;lastDet=d;if(!locked)$('#scanStatus').innerHTML=d.stable?'<span class=good>✓ Carta agganciata</span>':'Carta rilevata…';if(rapid&&d.stable&&!busy&&!locked)scanDetected(d);}else{missing++;if(missing<4&&lastDet){if(!locked)$('#scanStatus').textContent='Mantengo l’aggancio…';return}lastDet=null;if(missing>=4){locked=false;clearDuplicateUI();lastCode='';}if(!locked)$('#scanStatus').textContent='Cerco i bordi della carta…';}},220);};
scanDetected=async function(d){if(busy||locked)return;busy=true;try{const wc=warpDetected(d),w=await ocr();const top1=(await w.recognize(cropCanvas(wc,.02,.25))).data.text||'';const top2=(await w.recognize(cropRegion(wc,.02,.03,.98,.31,2.2))).data.text||'';const bottom=(await w.recognize(cropCanvas(wc,.68,.995))).data.text||'';let exact=null,cands=[],provisional=false,extra='';
if(game==='onepiece'){
  const codeText=(await w.recognize(cropRegion(wc,.48,.76,.995,.995,4),{tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789- '})).data.text||'';extra='CODE ZONE:\n'+codeText;const code=extractOPCode(codeText+' '+bottom);if(code){const found=await findOP(code);if(found.length)exact=found[0];}
}else if(game==='pokemon'){
  const p=relaxedPokemonNumber(bottom);if(p){const found=await findPK(p,top1+'\n'+top2);if(found.length===1)exact=found[0];}
}else{
  const mb=magicBottom(bottom);const found=await findMagic(top1+'\n'+top2,mb);if(found.length===1)exact=found[0];
}
let name1=bestName(top1),name2=bestName(top2);if(exact){cands=[exact];}else if(name1&&name2&&namesClose(name1,name2)){const agreed=name1.length>=name2.length?name1:name2;cands=await searchByName(agreed);if(cands.length){provisional=true;cands=cands.filter(x=>namesClose(agreed,x.name));}}
showOcr(top1+'\n--- SECOND PASS ---\n'+top2,bottom,'',extra);
if(!cands.length){locked=true;$('#scanStatus').innerHTML='<span class=bad>Carta vista, ma il nome non è abbastanza sicuro. Nessuna carta aggiunta. Rimuovila e riprova.</span>';return;}
const card=cands[0];const last=getLastCard();if(last&&namesClose(last.name,card.name)){locked=true;showDuplicate(card,provisional);return;}
locked=true;if(provisional){addProvisional(card);$('#scanStatus').innerHTML='<span class=good>✓ '+esc(card.name)+' aggiunta • stampa da verificare. Ora rimuovi la carta.</span>';}else{addExact(card);$('#scanStatus').innerHTML='<span class=good>✓ '+esc(card.name)+' • '+esc(card.collector||'')+' acquisita. Ora rimuovi la carta.</span>';}stableFrames=0;lastQuad=null;
}catch(e){locked=true;$('#scanStatus').innerHTML='<span class=bad>Errore riconoscimento: '+esc(e.message)+'</span>';}finally{busy=false;}};
})();