/* WallKeep recognition patch v5 */
(function(){
const genericWords=new Set(['set','card','carta','the','di','del','edition','edizione']);
function qTokens(q){return String(q||'').toLowerCase().replace(/[–—]/g,'-').split(/[^a-z0-9'-]+/).filter(t=>t.length>1&&!genericWords.has(t));}
function normText(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ');}
function allTokensMatch(r,q){const ts=qTokens(q),hay=normText([r.name,r.setName,r.setCode,r.collector].join(' '));return ts.every(t=>hay.includes(normText(t).trim()));}
function numericTokens(q){return qTokens(q).filter(t=>/\d/.test(t));}
function meaningfulLine(text){const bad=/^(basic|stage|trainer|supporter|item|energy|creature|instant|sorcery|artifact|enchantment|legendary|character|leader|event|stage)$/i;return String(text||'').split(/\r?\n/).map(x=>x.replace(/[^A-Za-z0-9.'’\- ]/g,' ').replace(/\s+/g,' ').trim()).filter(x=>x.length>=3&&!bad.test(x)).sort((a,b)=>{const aw=/^[A-Za-z][A-Za-z.'’\- ]+$/.test(a)?10:0,bw=/^[A-Za-z][A-Za-z.'’\- ]+$/.test(b)?10:0;return bw-aw||a.length-b.length;})[0]||'';}
async function getPokemonDetails(list){const out=[];for(const b of(Array.isArray(list)?list:[]).slice(0,120)){try{const d=await json(`https://api.tcgdex.net/v2/en/cards/${encodeURIComponent(b.id)}`);out.push({name:d.name||b.name,setName:d.set?.name||'',setCode:d.set?.id||'',collector:d.localId||b.localId||'',image:d.image?d.image+'/high.webp':b.image||'',externalId:d.id});}catch(e){}}return out;}
searchPokemon=async function(q){const ts=qTokens(q);if(!ts.length)return[];const nameToken=ts.find(t=>!/\d/.test(t)&&!/^(sv|swsh|sm|xy|bw|hgss|dp|pl|ex)\d*$/i.test(t))||ts[0];let arr=[];try{arr=await json(`https://api.tcgdex.net/v2/en/cards?name=${encodeURIComponent(nameToken)}`)}catch(e){return[]}let out=await getPokemonDetails(arr);const strict=out.filter(r=>allTokensMatch(r,q));if(strict.length)out=strict;else{const nums=numericTokens(q);if(nums.length){const byNum=out.filter(r=>nums.every(n=>normText(r.collector+' '+r.setCode).includes(normText(n).trim())));if(byNum.length)out=byNum;}}return out.sort((a,b)=>scoreResult(b,q)-scoreResult(a,q)).slice(0,40);};
searchOP=async function(q){let code=String(q).toUpperCase().match(/(?:OP|ST|EB|PRB)\s*-?\s*\d{1,2}(?:\s*-\s*\d{3})?/i)?.[0];if(code&&/-\s*\d{3}/.test(code)){let x=await findOP(code.replace(/\s/g,''));if(x.length)return x}const all=await loadOP();let out=all.filter(r=>allTokensMatch(r,q));if(!out.length){const ts=qTokens(q);out=all.filter(r=>ts.every(t=>normText(r.name+' '+r.setName+' '+r.setCode+' '+r.collector).includes(normText(t).trim())))}return out.sort((a,b)=>scoreResult(b,q)-scoreResult(a,q)).slice(0,40);};
searchMagic=async function(q){const ts=qTokens(q);if(!ts.length)return[];let named=null;for(let n=ts.length;n>=1&&!named;n--){const candidate=ts.slice(0,n).join(' ');try{named=await json(`https://api.scryfall.com/cards/named?fuzzy=${encodeURIComponent(candidate)}`)}catch(e){}}if(!named)return[];let prints=[];try{let d=await json(`https://api.scryfall.com/cards/search?q=${encodeURIComponent('!"'+named.name+'"')}&unique=prints&order=released`);prints=(d.data||[]).map(mapMagic)}catch(e){prints=[mapMagic(named)]}let strict=prints.filter(r=>allTokensMatch(r,q));if(strict.length)prints=strict;else prints.sort((a,b)=>scoreResult(b,q)-scoreResult(a,q));return prints.slice(0,40);};
function showOcr(top,bottom,full=''){let el=document.querySelector('#ocrDebug');if(!el){el=document.createElement('details');el.id='ocrDebug';el.className='panel';el.style.marginTop='8px';el.innerHTML='<summary style="cursor:pointer;color:#f3d17a;font-weight:700">Diagnostica OCR</summary><pre id="ocrDebugText" style="white-space:pre-wrap;font-size:11px;color:#aaa;margin:8px 0 0"></pre>';document.querySelector('#scanStatus').insertAdjacentElement('afterend',el)}el.querySelector('#ocrDebugText').textContent='TOP:\n'+top+'\n\nBOTTOM:\n'+bottom+(full?'\n\nFULL:\n'+full:'');}
function relaxedPokemonNumber(t){t=String(t||'').toUpperCase().replace(/O/g,'0');let m=t.match(/\b(\d{1,3}[A-Z]?)\s*[\/\\]\s*(\d{2,3})\b/);if(m)return{local:m[1],total:m[2]};m=t.match(/\b(\d{1,3})\s+(\d{3})\b/);return m?{local:m[1],total:m[2]}:null;}
async function pokemonByName(name,bottom){if(!name)return[];let q=name;const p=relaxedPokemonNumber(bottom);if(p)q+=' '+p.local+' '+p.total;return searchPokemon(q);}
async function opByOcr(top,bottom){let code=op(bottom+' '+top);if(code){let x=await findOP(code);if(x.length)return x}const name=meaningfulLine(top),setFrag=(String(bottom).toUpperCase().match(/\b(?:OP|ST|EB|PRB)\s*-?\s*\d{1,2}\b/)||[])[0]||'';if(name)return searchOP(name+' '+setFrag.replace(/\s/g,''));return[];}
async function magicByOcr(top,bottom){const mb=magicBottom(bottom);let x=await findMagic(top,mb);if(x.length)return x;const name=meaningfulLine(top);if(!name)return[];return searchMagic(name+' '+(mb.set||'')+' '+(mb.collector||''));}
scanDetected=async function(d){if(busy)return;busy=true;try{const wc=warpDetected(d),w=await ocr();const top=(await w.recognize(cropCanvas(wc,.02,.23))).data.text||'',bottom=(await w.recognize(cropCanvas(wc,.76,.995))).data.text||'';let cands=[],code='';if(game==='onepiece')cands=await opByOcr(top,bottom);else if(game==='pokemon'){let p=relaxedPokemonNumber(bottom);if(p){code=p.local+'/'+p.total;cands=await findPK(p,top)}if(!cands.length)cands=await pokemonByName(meaningfulLine(top),bottom);}else cands=await magicByOcr(top,bottom);let full='';if(!cands.length){full=(await w.recognize(cropCanvas(wc,.02,.995))).data.text||'';showOcr(top,bottom,full);if(game==='onepiece')cands=await opByOcr(top+'\n'+full,bottom+'\n'+full);else if(game==='pokemon')cands=await pokemonByName(meaningfulLine(top+'\n'+full),bottom+'\n'+full);else cands=await magicByOcr(top+'\n'+full,bottom+'\n'+full);}else showOcr(top,bottom);if(!cands.length){$('#scanStatus').innerHTML='<span class=bad>Carta agganciata, ma non identificata. Apri “Diagnostica OCR” qui sotto.</span>';return}code=cands[0].externalId||cands[0].collector||meaningfulLine(top);if(code===lastCode){$('#scanStatus').textContent='Carta già acquisita: sostituiscila.';return}lastCode=code;add(cands[0],cands);$('#scanStatus').innerHTML='<span class=good>✓ '+esc(cands[0].name)+' acquisita'+(cands.length>1?' • stampa da verificare':'')+'. Carta successiva.</span>';stableFrames=0;lastQuad=null;}catch(e){$('#scanStatus').innerHTML='<span class=bad>Errore riconoscimento: '+esc(e.message)+'</span>'}finally{busy=false}};
})();