/* WallKeep Google Vision backend bridge */
(function(){
const ENDPOINT_KEY='wallkeep.visionEndpoint';
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function textScore(card,text){const hay=norm([card.name,card.setCode,card.setName,card.collector].join(' ')),ts=norm(text).split(/\s+/).filter(x=>x.length>2);let s=0;for(const t of ts){if(hay.includes(t))s+=card.name&&norm(card.name).includes(t)?4:1;}return s;}
function frozenJpeg(canvas){const c=document.createElement('canvas'),ctx=c.getContext('2d'),max=1100,scale=Math.min(1,max/canvas.width);c.width=Math.max(1,Math.round(canvas.width*scale));c.height=Math.max(1,Math.round(canvas.height*scale));ctx.drawImage(canvas,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.86);}
function lastCard(){return current()?.cards?.[0]||null;}
function closeName(a,b){a=norm(a);b=norm(b);return !!a&&!!b&&(a===b||a.includes(b)||b.includes(a));}
function addCandidate(card){const l=current();l.game=game;l.name=$('#scanListName').value||l.name;l.cards.unshift({id:crypto.randomUUID?crypto.randomUUID():Date.now()+''+Math.random(),game:game==='pokemon'?'Pokémon':game==='onepiece'?'One Piece':'Magic',quantity:1,condition:'',language:'',foil:'',price:'',resolved:false,needsReview:true,visionScore:card.score??null,...card});save();navigator.vibrate?.([50,30,50]);}
function showDuplicate(card){document.querySelector('#duplicateBtn')?.remove();const b=document.createElement('button');b.id='duplicateBtn';b.className='btn w100';b.style.marginTop='8px';b.textContent='+ AGGIUNGI UN’ALTRA COPIA DI '+String(card.name||'').toUpperCase();b.onclick=()=>{const l=lastCard();if(l&&closeName(l.name,card.name)){l.quantity=(+l.quantity||1)+1;save();}else addCandidate(card);b.remove();$('#scanStatus').innerHTML='<span class=good>✓ Copia aggiunta. Rimuovi la carta.</span>';};$('#scanStatus').insertAdjacentElement('afterend',b);$('#scanStatus').innerHTML='<span class=bad>'+esc(card.name)+' è uguale alla precedente. Tocca il pulsante solo per confermare un’altra copia.</span>';}
async function ocrText(canvas){try{const w=await ocr();const top=(await w.recognize(cropCanvas(canvas,.00,.34))).data.text||'';const bottom=(await w.recognize(cropCanvas(canvas,.58,1))).data.text||'';return top+'\n'+bottom;}catch(e){return'';}}
async function visionSearch(canvas){const endpoint=(localStorage.getItem(ENDPOINT_KEY)||'').trim().replace(/\/$/,'');if(!endpoint)throw new Error('Backend Vision non configurato');const img=frozenJpeg(canvas),text=await ocrText(canvas);const r=await fetch(endpoint+'/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({game,imageBase64:img,maxResults:18})});const d=await r.json();if(!r.ok)throw new Error(d.error||('HTTP '+r.status));let c=(d.candidates||[]).map(x=>({...x,_combined:(Number(x.score)||0)*100+textScore(x,text)*4}));c.sort((a,b)=>b._combined-a._combined);return{candidates:c,text};}
const previousScan=scanDetected;
scanDetected=async function(d){const endpoint=(localStorage.getItem(ENDPOINT_KEY)||'').trim();if(!endpoint)return previousScan(d);if(busy)return;busy=true;try{const frozen=warpDetected(d);$('#scanStatus').textContent='Fotogramma congelato • riconoscimento visivo…';const result=await visionSearch(frozen),card=result.candidates[0];let el=document.querySelector('#ocrDebug');if(!el){el=document.createElement('details');el.id='ocrDebug';el.className='panel';el.innerHTML='<summary style="cursor:pointer;color:#f3d17a;font-weight:700">Diagnostica OCR</summary><pre id="ocrDebugText" style="white-space:pre-wrap;font-size:11px;color:#aaa"></pre>';$('#scanStatus').insertAdjacentElement('afterend',el)}el.querySelector('#ocrDebugText').textContent='OCR:\n'+result.text+'\n\nVISION TOP:\n'+result.candidates.slice(0,5).map((x,i)=>`${i+1}. ${x.name} | ${x.setCode} ${x.collector} | ${(x.score*100).toFixed(1)}%`).join('\n');if(!card){$('#scanStatus').innerHTML='<span class=bad>Nessun candidato visivo trovato.</span>';return;}const last=lastCard();if(last&&closeName(last.name,card.name)){showDuplicate(card);return;}addCandidate(card);$('#scanStatus').innerHTML='<span class=good>✓ '+esc(card.name)+' aggiunta • risultato visivo '+(card.score!=null?(card.score*100).toFixed(1)+'%':'')+' • stampa da verificare.</span>';stableFrames=0;lastQuad=null;}catch(e){$('#scanStatus').innerHTML='<span class=bad>Vision: '+esc(e.message)+'</span>';}finally{busy=false;}};

function ensureVisionSettings(){const settings=document.querySelector('#settings .panel');if(!settings||document.querySelector('#visionEndpoint'))return;const box=document.createElement('div');box.style.marginTop='16px';box.innerHTML='<h3 class="title">Riconoscimento visivo</h3><p class="muted">URL HTTPS del backend WallKeep Vision.</p><input id="visionEndpoint" placeholder="https://...run.app" value="'+(localStorage.getItem(ENDPOINT_KEY)||'')+'"><div class="row" style="margin-top:8px"><button id="saveVisionEndpoint" class="btn grow">SALVA VISION</button><button id="testVisionEndpoint" class="btn secondary">TEST</button></div>';settings.appendChild(box);box.querySelector('#saveVisionEndpoint').onclick=()=>{localStorage.setItem(ENDPOINT_KEY,box.querySelector('#visionEndpoint').value.trim());alert('Backend Vision salvato')};box.querySelector('#testVisionEndpoint').onclick=async()=>{try{const u=box.querySelector('#visionEndpoint').value.trim().replace(/\/$/,'');const r=await fetch(u+'/health'),d=await r.json();alert(d.ok?'WallKeep Vision collegato':'Backend non pronto')}catch(e){alert('Vision: '+e.message)}};}
setTimeout(ensureVisionSettings,500);
})();
