/* WallKeep visual recognition pipeline v9 */
(function(){
const P=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
let wk9Busy=false,wk9Locked=false,wk9Missing=0,wk9Seen=0,wk9LastDet=null;
const bad=/^(character|leader|event|stage|on play|activate main|trigger|counter|land of wano|trainer|supporter|item|energy|basic|stage 1|stage 2)$/i;
function textLines(s){return String(s||'').split(/\r?\n/).map(x=>x.replace(/[^A-Za-z0-9.'’\- ]/g,' ').replace(/\s+/g,' ').trim()).filter(x=>x.length>=3&&!bad.test(x)&&!/^\d+[A-Za-z ]*$/.test(x));}
function closeName(a,b){a=P(a);b=P(b);if(!a||!b)return false;if(a===b||a.includes(b)||b.includes(a))return true;const aa=new Set(a.split(' ')),bb=new Set(b.split(' '));return [...aa].filter(x=>x.length>2&&bb.has(x)).length>=1;}
function lastCard(){return current()?.cards?.[0]||null;}
function clearDuplicate(){document.querySelector('#duplicateBtn')?.remove();}
function addReview(card,meta={}){const l=current();l.game=game;l.name=$('#scanListName').value||l.name;l.cards.unshift({id:crypto.randomUUID?crypto.randomUUID():Date.now()+''+Math.random(),game:game==='pokemon'?'Pokémon':game==='onepiece'?'One Piece':'Magic',quantity:1,condition:'',language:'',foil:'',price:'',resolved:false,needsReview:true,...meta,...card});save();navigator.vibrate?.([50,30,50]);}
function duplicatePrompt(card,meta={}){clearDuplicate();const b=document.createElement('button');b.id='duplicateBtn';b.className='btn w100';b.style.marginTop='8px';b.textContent='+ AGGIUNGI UN’ALTRA COPIA DI '+card.name.toUpperCase();b.onclick=()=>{const l=lastCard();if(l&&closeName(l.name,card.name)){l.quantity=(+l.quantity||1)+1;save();}else addReview(card,meta);clearDuplicate();wk9Locked=true;$('#scanStatus').innerHTML='<span class=good>✓ Copia aggiunta. Rimuovi la carta.</span>';};$('#scanStatus').insertAdjacentElement('afterend',b);$('#scanStatus').innerHTML='<span class=bad>'+esc(card.name)+' coincide con la carta precedente. Tocca il pulsante solo per aggiungere un’altra copia.</span>';}

function expandedWarp(d){
  const q=d.q,topMid={x:(q[0].x+q[1].x)/2,y:(q[0].y+q[1].y)/2},botMid={x:(q[3].x+q[2].x)/2,y:(q[3].y+q[2].y)/2},leftMid={x:(q[0].x+q[3].x)/2,y:(q[0].y+q[3].y)/2},rightMid={x:(q[1].x+q[2].x)/2,y:(q[1].y+q[2].y)/2};
  let hx=rightMid.x-leftMid.x,hy=rightMid.y-leftMid.y,hw=Math.hypot(hx,hy)||1;hx/=hw;hy/=hw;
  let vx=botMid.x-topMid.x,vy=botMid.y-topMid.y,vh=Math.hypot(vx,vy)||1;vx/=vh;vy/=vh;
  const cx=(q[0].x+q[1].x+q[2].x+q[3].x)/4,cy=(q[0].y+q[1].y+q[2].y+q[3].y)/4;
  let outerW=hw*1.28,outerH=outerW*1.397;const c=$('#detectCanvas');if(outerH>c.height*.98){outerH=c.height*.98;outerW=outerH/1.397}if(outerW>c.width*.98){outerW=c.width*.98;outerH=outerW*1.397}
  const pts=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([sx,sy])=>({x:Math.max(0,Math.min(c.width-1,cx+hx*outerW*.5*sx+vx*outerH*.5*sy)),y:Math.max(0,Math.min(c.height-1,cy+hy*outerW*.5*sx+vy*outerH*.5*sy))}));
  let src=cv.imread(c),dst=new cv.Mat(),sp=cv.matFromArray(4,1,cv.CV_32FC2,pts.flatMap(p=>[p.x,p.y])),dp=cv.matFromArray(4,1,cv.CV_32FC2,[0,0,744,0,744,1039,0,1039]),M=cv.getPerspectiveTransform(sp,dp);cv.warpPerspective(src,dst,M,new cv.Size(744,1039),cv.INTER_LINEAR,cv.BORDER_REPLICATE);cv.imshow('warpCanvas',dst);src.delete();dst.delete();sp.delete();dp.delete();M.delete();return $('#warpCanvas');
}
function rgb2hsv(r,g,b){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn;let h=0;if(d){if(mx===r)h=((g-b)/d)%6;else if(mx===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360}return[h,mx?d/mx:0,mx];}
function frameFeature(canvas){const c=document.createElement('canvas'),x=c.getContext('2d',{willReadFrequently:true}),W=60,H=84;c.width=W;c.height=H;x.drawImage(canvas,0,0,W,H);const d=x.getImageData(0,0,W,H).data,bins=new Array(8).fill(0);let dark=0,sat=0,n=0;for(let yy=0;yy<H;yy++)for(let xx=0;xx<W;xx++){if(xx>6&&xx<W-7&&yy>8&&yy<H-15)continue;const i=(yy*W+xx)*4,[h,s,v]=rgb2hsv(d[i],d[i+1],d[i+2]);n++;sat+=s;if(v<.27)dark++;if(s>.28&&v>.25)bins[Math.floor(h/45)%8]++;}bins.forEach((_,i)=>bins[i]/=Math.max(1,n));return{dark:dark/n,sat:sat/n,bins};}
function colorDistance(a,b){let z=Math.abs(a.dark-b.dark)*4+Math.abs(a.sat-b.sat)*.7;for(let i=0;i<8;i++)z+=Math.abs(a.bins[i]-b.bins[i])*2.2;if(a.dark>.42&&b.dark<.22)z+=3.2;if(b.dark>.42&&a.dark<.22)z+=3.2;return z;}
function artFeature(canvas){const c=document.createElement('canvas'),x=c.getContext('2d',{willReadFrequently:true}),W=24,H=30;c.width=W;c.height=H;x.drawImage(canvas,canvas.width*.06,canvas.height*.05,canvas.width*.88,canvas.height*.64,0,0,W,H);const d=x.getImageData(0,0,W,H).data,v=[];for(let i=0;i<d.length;i+=4)v.push([d[i]/255,d[i+1]/255,d[i+2]/255]);return v;}
function artDistance(a,b){let s=0,n=Math.min(a.length,b.length);for(let i=0;i<n;i++)s+=(Math.abs(a[i][0]-b[i][0])+Math.abs(a[i][1]-b[i][1])+Math.abs(a[i][2]-b[i][2]))/3;return s/Math.max(1,n);}
function loadImg(url){return new Promise((ok,no)=>{const im=new Image();im.crossOrigin='anonymous';im.onload=()=>ok(im);im.onerror=no;im.src=url;});}
async function candidateFeatures(card){if(!card.image)return null;try{const im=await loadImg(card.image),c=document.createElement('canvas'),x=c.getContext('2d');c.width=im.naturalWidth||744;c.height=im.naturalHeight||1039;x.drawImage(im,0,0,c.width,c.height);return{frame:frameFeature(c),art:artFeature(c)}}catch(e){return null}}
async function rankVisual(scan,candidates,textName='',setHint=''){const sf=frameFeature(scan),sa=artFeature(scan),out=[];let idx=0;const worker=async()=>{while(idx<candidates.length){const i=idx++,card=candidates[i],f=await candidateFeatures(card);if(!f)continue;const cd=colorDistance(sf,f.frame),ad=artDistance(sa,f.art);let tp=0;if(textName){if(closeName(textName,card.name))tp-=1.25;else tp+=.55}if(setHint){if(String(card.setCode||'').toUpperCase()===setHint)tp-=.9;else tp+=1.2}out.push({...card,_frame:cd,_art:ad,_score:cd*1.9+ad*2.5+tp});}};await Promise.all(Array.from({length:Math.min(8,candidates.length)},worker));out.sort((a,b)=>a._score-b._score);return out;}
function exactOPCode(t){const s=String(t||'').toUpperCase().replace(/[–—_]/g,'-').replace(/\s+/g,' ').replace(/O(?=\d)/g,'0').replace(/[IL](?=\d)/g,'1');let m=s.match(/\b((?:OP|ST|EB|PRB)\s*-?\s*\d{1,2}\s*-\s*\d{3})\b/);return m?m[1].replace(/\s/g,'').replace(/^([A-Z]+)-?(\d+)-/,'$1$2-'):null;}
function opSetHint(t){let s=String(t||'').toUpperCase().replace(/[^A-Z0-9]/g,'');let m=s.match(/(?:OP|0P)(\d{1,2})/);if(m)return'OP'+String(+m[1]).padStart(2,'0');m=s.match(/(?:^|[^A-Z])P(\d{2})\d{0,3}/);if(m)return'OP'+m[1];m=s.match(/P(\d{2})\d{1,3}/);return m?'OP'+m[1]:'';}
async function nameCandidates(text){for(const line of textLines(text).slice(0,12)){try{let a=game==='onepiece'?await searchOP(line):game==='pokemon'?await searchPokemon(line):await searchMagic(line);a=(a||[]).filter(x=>closeName(line,x.name));if(a.length)return{name:a[0].name,cards:a};}catch(e){}}return{name:'',cards:[]};}
function uniqueCards(arr){const m=new Map();for(const c of arr||[])if(c&&(c.externalId||c.collector))m.set(c.externalId||c.collector,c);return [...m.values()];}
function debug(top,bottom,full,info){let el=document.querySelector('#ocrDebug');if(!el){el=document.createElement('details');el.id='ocrDebug';el.className='panel';el.style.marginTop='8px';el.innerHTML='<summary style="cursor:pointer;color:#f3d17a;font-weight:700">Diagnostica OCR</summary><pre id="ocrDebugText" style="white-space:pre-wrap;font-size:11px;color:#aaa;margin:8px 0 0"></pre>';document.querySelector('#scanStatus').insertAdjacentElement('afterend',el)}el.querySelector('#ocrDebugText').textContent=info+'\n\nTOP:\n'+top+'\n\nBOTTOM:\n'+bottom+'\n\nFULL:\n'+full;}
async function identifyOP(frozen){const w=await ocr();$('#scanStatus').textContent='Fotogramma congelato • OCR e immagine in analisi…';const top=(await w.recognize(cropCanvas(frozen,.00,.34))).data.text||'',bottom=(await w.recognize(cropCanvas(frozen,.56,1))).data.text||'',full=(await w.recognize(cropCanvas(frozen,.00,1))).data.text||'',all=top+'\n'+bottom+'\n'+full;const code=exactOPCode(all),hint=opSetHint(all);if(code){const f=await findOP(code);if(f.length){debug(top,bottom,full,'EXACT: '+code);return{card:f[0],exact:true,meta:{recognition:'exact'}}}}
const nh=await nameCandidates(all);let pool=[...(nh.cards||[])];if(hint){try{const allCards=await loadOP();pool.push(...allCards.filter(c=>String(c.setCode||'').toUpperCase()===hint));}catch(e){}}
pool=uniqueCards(pool);if(!pool.length){debug(top,bottom,full,'NAME: '+(nh.name||'non trovato')+'\nSET HINT: '+(hint||'non trovato'));return{card:null};}
$('#scanStatus').textContent='Candidati '+pool.length+' • confronto colore e artwork…';const ranked=await rankVisual(frozen,pool.slice(0,180),nh.name,hint),best=ranked[0];debug(top,bottom,full,'NAME OCR: '+(nh.name||'nessuno')+'\nSET HINT: '+(hint||'nessuno')+(best?'\nBEST: '+best.name+' / '+best.setName+' / '+best.collector+'\nFRAME DIST: '+best._frame.toFixed(3)+'\nART DIST: '+best._art.toFixed(3)+'\nTOTAL: '+best._score.toFixed(3):''));return{card:best||null,exact:false,meta:{recognition:'visual',visualScore:best?best._score:null,setHint:hint||'',ocrName:nh.name||''}};}
async function identifyOther(frozen){const w=await ocr(),top=(await w.recognize(cropCanvas(frozen,.00,.34))).data.text||'',bottom=(await w.recognize(cropCanvas(frozen,.56,1))).data.text||'',full=(await w.recognize(cropCanvas(frozen,.00,1))).data.text||'';if(game==='pokemon'){let p=pk(bottom+'\n'+full);if(p){let a=await findPK(p,top+'\n'+full);if(a.length)return{card:a[0],exact:a.length===1,meta:{recognition:'number'}}}let n=await nameCandidates(top+'\n'+bottom+'\n'+full);if(n.cards.length){let r=await rankVisual(frozen,n.cards.slice(0,80),n.name,'');return{card:r[0]||n.cards[0],exact:false,meta:{recognition:'visual',visualScore:r[0]?._score??null}}}}else{const mb=magicBottom(bottom+'\n'+full),a=await findMagic(top+'\n'+full,mb);if(a.length===1)return{card:a[0],exact:true,meta:{recognition:'exact'}};let n=await nameCandidates(top+'\n'+bottom+'\n'+full);if(n.cards.length){let r=await rankVisual(frozen,n.cards.slice(0,80),n.name,'');return{card:r[0]||n.cards[0],exact:false,meta:{recognition:'visual',visualScore:r[0]?._score??null}}}}return{card:null};}
scanDetected=async function(d){if(wk9Busy||wk9Locked)return;wk9Busy=true;try{const frozen=expandedWarp(d),res=game==='onepiece'?await identifyOP(frozen):await identifyOther(frozen);if(!res.card){wk9Locked=true;$('#scanStatus').innerHTML='<span class=bad>Nessun risultato plausibile. Rimuovi la carta e riprova oppure aggiungila a mano.</span>';return}const last=lastCard();if(last&&closeName(last.name,res.card.name)){wk9Locked=true;duplicatePrompt(res.card,res.meta);return}wk9Locked=true;if(res.exact){add(res.card,[res.card]);$('#scanStatus').innerHTML='<span class=good>✓ '+esc(res.card.name)+' acquisita. Rimuovi la carta.</span>';}else{addReview(res.card,res.meta);$('#scanStatus').innerHTML='<span class=good>✓ '+esc(res.card.name)+' aggiunta • stampa da verificare. Rimuovi la carta.</span>';}stableFrames=0;lastQuad=null;}catch(e){wk9Locked=true;$('#scanStatus').innerHTML='<span class=bad>Errore riconoscimento: '+esc(e.message)+'</span>';}finally{wk9Busy=false;}};
const detect9=detectCard;startDetection=function(){clearInterval(detectTimer);detectTimer=setInterval(()=>{const d=detect9();if(d){wk9Missing=0;wk9LastDet=d;wk9Seen++;if(!wk9Locked)$('#scanStatus').textContent=wk9Seen>=3?'Carta stabile • congelo il fotogramma…':'Carta rilevata…';if(rapid&&!wk9Busy&&!wk9Locked&&wk9Seen>=3)scanDetected({...d,stable:true});}else{wk9Missing++;wk9Seen=0;if(wk9Missing<5&&wk9LastDet){if(!wk9Locked)$('#scanStatus').textContent='Mantengo l’aggancio…';return}wk9LastDet=null;if(wk9Missing>=5){wk9Locked=false;clearDuplicate();lastCode='';}if(!wk9Locked)$('#scanStatus').textContent='Cerco la carta…';}},220);};
})();