/* WallKeep visual recognition pipeline v8 */
(function(){
const N=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const badLine=/^(character|leader|event|stage|on play|activate main|trigger|counter|land of wano|trainer|supporter|item|energy|basic|stage 1|stage 2)$/i;
let v8Busy=false,v8Locked=false,v8Missing=0,v8Seen=0,v8LastDet=null,v8PendingDuplicate=null;

function linesOf(s){return String(s||'').split(/\r?\n/).map(x=>x.replace(/[^A-Za-z0-9.'’\- ]/g,' ').replace(/\s+/g,' ').trim()).filter(x=>x.length>=3&&!badLine.test(x)&&!/^\d+[A-Za-z ]*$/.test(x));}
function closeName(a,b){a=N(a);b=N(b);return !!a&&!!b&&(a===b||a.includes(b)||b.includes(a));}
function lastCard(){return current()?.cards?.[0]||null;}
function clearDup(){v8PendingDuplicate=null;document.querySelector('#duplicateBtn')?.remove();}
function addProvisional(card,score){const l=current();l.game=game;l.name=$('#scanListName').value||l.name;l.cards.unshift({id:crypto.randomUUID?crypto.randomUUID():Date.now()+''+Math.random(),game:game==='pokemon'?'Pokémon':game==='onepiece'?'One Piece':'Magic',quantity:1,condition:'',language:'',foil:'',price:'',resolved:false,needsReview:true,visualScore:score??null,...card});save();navigator.vibrate?.([50,30,50]);}
function showDup(card,score){clearDup();v8PendingDuplicate={card,score};const b=document.createElement('button');b.id='duplicateBtn';b.className='btn w100';b.style.marginTop='8px';b.textContent='+ AGGIUNGI UN’ALTRA COPIA DI '+card.name.toUpperCase();b.onclick=()=>{const last=lastCard();if(last&&closeName(last.name,card.name)){last.quantity=(+last.quantity||1)+1;save();}else addProvisional(card,score);clearDup();v8Locked=true;$('#scanStatus').innerHTML='<span class=good>✓ Copia aggiunta. Rimuovi la carta per continuare.</span>';};$('#scanStatus').insertAdjacentElement('afterend',b);$('#scanStatus').innerHTML='<span class=bad>'+esc(card.name)+' è uguale alla precedente. Aggiungo un’altra copia solo se tocchi il pulsante.</span>';}

function canvasFeature(canvas,crop={x:.08,y:.08,w:.84,h:.72}){const c=document.createElement('canvas'),ctx=c.getContext('2d',{willReadFrequently:true}),W=32,H=32;c.width=W;c.height=H;ctx.drawImage(canvas,canvas.width*crop.x,canvas.height*crop.y,canvas.width*crop.w,canvas.height*crop.h,0,0,W,H);const d=ctx.getImageData(0,0,W,H).data,hist=new Array(24).fill(0),lum=[];for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2];hist[Math.min(7,r>>5)]++;hist[8+Math.min(7,g>>5)]++;hist[16+Math.min(7,b>>5)]++;lum.push((r*3+g*6+b)/10);}const sum=W*H;for(let i=0;i<hist.length;i++)hist[i]/=sum;return{hist,lum};}
function featureDistance(a,b){let h=0;for(let i=0;i<a.hist.length;i++)h+=Math.abs(a.hist[i]-b.hist[i]);let l=0;for(let i=0;i<a.lum.length;i++)l+=Math.abs(a.lum[i]-b.lum[i])/255;return h*.55+(l/a.lum.length)*.45;}
function loadImage(url){return new Promise((resolve,reject)=>{const im=new Image();im.crossOrigin='anonymous';im.onload=()=>resolve(im);im.onerror=reject;im.src=url;});}
async function candidateFeature(card){if(!card.image)return null;try{const im=await loadImage(card.image),c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=im.naturalWidth||744;c.height=im.naturalHeight||1039;ctx.drawImage(im,0,0,c.width,c.height);let crop=game==='magic'?{x:.07,y:.17,w:.86,h:.48}:game==='pokemon'?{x:.07,y:.20,w:.86,h:.42}:{x:.07,y:.08,w:.86,h:.70};return canvasFeature(c,crop);}catch(e){return null;}}
async function visualRank(scanCanvas,candidates){if(!candidates?.length)return[];const scanF=canvasFeature(scanCanvas,{x:.02,y:.02,w:.96,h:.90}),out=[];for(const c of candidates.slice(0,24)){const f=await candidateFeature(c);if(!f){out.push({...c,_visual:999});continue}out.push({...c,_visual:featureDistance(scanF,f)});}out.sort((a,b)=>a._visual-b._visual);return out;}

async function dbSearchName(name){try{if(game==='onepiece')return await searchOP(name);if(game==='pokemon')return await searchPokemon(name);return await searchMagic(name);}catch(e){return[];}}
async function resolveNameFromText(text){const ls=linesOf(text);let best=null;for(const line of ls.slice(0,10)){let found=await dbSearchName(line);if(!found.length)continue;const exact=found.filter(x=>closeName(line,x.name));if(exact.length){best={name:exact[0].name,candidates:exact};break;}}return best;}
function opCode(t){const s=String(t||'').toUpperCase().replace(/[–—_]/g,'-').replace(/\s+/g,' ').replace(/O(?=\d)/g,'0').replace(/[IL](?=\d)/g,'1');let m=s.match(/\b((?:OP|ST|EB|PRB)\s*-?\s*\d{1,2}\s*-\s*\d{3})\b/);if(m)return m[1].replace(/\s/g,'').replace(/^([A-Z]+)-?(\d+)-/,'$1$2-');m=s.match(/\b(P\s*-\s*\d{3})\b/);return m?m[1].replace(/\s/g,''):null;}
function pkNo(t){t=String(t||'').toUpperCase().replace(/O/g,'0');const m=t.match(/\b(\d{1,3}[A-Z]?)\s*[\/\\]\s*(\d{2,3})\b/);return m?{local:m[1],total:m[2]}:null;}

async function identifyFrozen(wc){const w=await ocr();$('#scanStatus').textContent='Fotogramma acquisito • leggo i dati…';const top=(await w.recognize(cropCanvas(wc,.00,.34))).data.text||'';const bottom=(await w.recognize(cropCanvas(wc,.58,1))).data.text||'';const full=(await w.recognize(cropCanvas(wc,.00,1))).data.text||'';let exact=null,allText=top+'\n'+bottom+'\n'+full,debug='';
if(game==='onepiece'){const code=opCode(allText);if(code){const f=await findOP(code);if(f.length)exact=f[0];}debug='ONE PIECE CODE: '+(code||'non letto');}
else if(game==='pokemon'){const p=pkNo(allText);if(p){const f=await findPK(p,top+'\n'+full);if(f.length===1)exact=f[0];}debug='POKEMON NUMBER: '+(p?p.local+'/'+p.total:'non letto');}
else{const mb=magicBottom(bottom+'\n'+full);const f=await findMagic(top+'\n'+full,mb);if(f.length===1)exact=f[0];debug='MAGIC: '+(mb.set||'?')+' / '+(mb.collector||'?');}
let nameHit=await resolveNameFromText(bottom+'\n'+top+'\n'+full);let candidates=[];
if(exact)candidates=[exact];else if(nameHit)candidates=nameHit.candidates;
let ranked=candidates;
if(!exact&&candidates.length>1){$('#scanStatus').textContent='Nome trovato: '+nameHit.name+' • confronto artwork…';ranked=await visualRank(wc,candidates);}
let el=document.querySelector('#ocrDebug');if(!el){el=document.createElement('details');el.id='ocrDebug';el.className='panel';el.style.marginTop='8px';el.innerHTML='<summary style="cursor:pointer;color:#f3d17a;font-weight:700">Diagnostica OCR</summary><pre id="ocrDebugText" style="white-space:pre-wrap;font-size:11px;color:#aaa;margin:8px 0 0"></pre>';document.querySelector('#scanStatus').insertAdjacentElement('afterend',el)}el.querySelector('#ocrDebugText').textContent=debug+'\n\nTOP:\n'+top+'\n\nBOTTOM:\n'+bottom+'\n\nFULL:\n'+full+(ranked?.[0]?('\n\nBEST VISUAL: '+ranked[0].name+' / '+ranked[0].setName+' / '+ranked[0].collector+'\nVISUAL SCORE: '+(ranked[0]._visual??'exact')):'');
return{card:ranked?.[0]||null,exact:!!exact,score:ranked?.[0]?._visual??null,name:nameHit?.name||exact?.name||''};}

scanDetected=async function(d){if(v8Busy||v8Locked)return;v8Busy=true;try{const frozen=warpDetected(d);$('#scanStatus').textContent='Fotogramma congelato…';const result=await identifyFrozen(frozen);if(!result.card){v8Locked=true;$('#scanStatus').innerHTML='<span class=bad>Non ho trovato una corrispondenza plausibile. Rimuovi la carta e riprova oppure aggiungila a mano.</span>';return;}const card=result.card,last=lastCard();if(last&&closeName(last.name,card.name)){v8Locked=true;showDup(card,result.score);return;}v8Locked=true;if(result.exact){add(card,[card]);$('#scanStatus').innerHTML='<span class=good>✓ '+esc(card.name)+' acquisita. Rimuovi la carta per continuare.</span>';}else{addProvisional(card,result.score);$('#scanStatus').innerHTML='<span class=good>✓ '+esc(card.name)+' aggiunta • stampa plausibile da verificare'+(result.score!=null?' • confronto visivo eseguito':'')+'. Rimuovi la carta.</span>';}stableFrames=0;lastQuad=null;}catch(e){v8Locked=true;$('#scanStatus').innerHTML='<span class=bad>Errore: '+esc(e.message)+'</span>';}finally{v8Busy=false;}};

const detector=detectCard;
startDetection=function(){clearInterval(detectTimer);detectTimer=setInterval(()=>{const d=detector();if(d){v8Missing=0;v8LastDet=d;v8Seen++;if(!v8Locked)$('#scanStatus').textContent=v8Seen>=2?'Carta stabile • acquisisco immagine…':'Carta rilevata…';if(rapid&&!v8Busy&&!v8Locked&&v8Seen>=2)scanDetected({...d,stable:true});}else{v8Missing++;v8Seen=0;if(v8Missing<5&&v8LastDet){if(!v8Locked)$('#scanStatus').textContent='Mantengo l’aggancio…';return;}v8LastDet=null;if(v8Missing>=5){v8Locked=false;clearDup();lastCode='';}if(!v8Locked)$('#scanStatus').textContent='Cerco la carta…';}},220);};
})();